name: node_app
on:
    push:
        branches:
            - "master"
jobs:
    build:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
            - # Клонируйте код приложения в ОС
              name: Checkout
              uses: actions/checkout@v3
            - # Войдите в Docker Hub используя токен
              name: Login in Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - # Создайте экземпляр build kit builder
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - # Создайте образ контенера и отправьте его в Docker Hub с помощью тега clocbox
              name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
